image:
- macos
- Visual Studio 2019

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- sh: pip3 install tornado nose --user
- sh: pip3 install tox --user
- cmd: pip3 install tox

test_script:
- tox
