image:
- macos
- Visual Studio 2019

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

for:
-
  matrix:
    only:
      - image: macos

  install:
  - pip3 install tornado nose --user
  - pip3 install tox --user

  test_script:
  - tox

-
  matrix:
    only:
      - image: Visual Studio 2019

    install:
    - pip3 install tox

    test_script
    - tox
