image:
- macos
- Visual Studio 2019

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- pip install nose --user
- pip install tornado --user
- pip install tox

test_script:
- tox
