image:
#- macos
- Visual Studio 2019

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38
#  - TOXENV: py39

build: off

install:
- sh: export PATH=/Users/appveyor/Library/Python/3.7/bin:$PATH
- sh: pip3 install tornado nose --user
- sh: pip3 install tox --user
- cmd: pip install tox

test_script:
- tox
