image:
- macos
- Visual Studio 2019

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- pip3 install tornado nose
- pip3 install tox

test_script:
- tox
