name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pharmpy/pharmpy 
      uses: actions/checkout@v2
      with:
          path: pharmpy
    - name: Checkout pharmpy/pharmpy.github.io
      uses: actions/checkout@v2
      with:
        repository: pharmpy/pharmpy.github.io
        path: pharmpy.github.io
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel tox tox-gh-actions
        sudo apt install graphviz
    - name: Test with tox
      run: |
          cd pharmpy
          tox
      env:
        PLATFORM: ${{ matrix.platform }}
    - name: Build documentation
      run: |
          cd pharmpy
          tox -e apidoc
          tox -e docs
    - name: Build wheel
      run: |
          cd pharmpy
          python setup.py bdist_wheel
    - name: Build source package
      run: python setup.py sdist --formats=gztar
    - name: Prepare upload files
      run: |
        cd pharmpy
        mkdir upload
        cp dist/*.whl dist/*.tar.gz upload
    - name: Publish documentation
      run: |
          cp -RT pharmpy/dist/docs/ pharmpy.github.io/latest/
          cd pharmpy.github.io
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Documentation update"
          git push
#    - name: Publish package to PyPI
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
#        packages_dir: pharmpy/upload/
