name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout pharmpy/pharmpy
        uses: actions/checkout@v3
        with:
            path: pharmpy

      - name: Checkout pharmpy/pharmpy.github.io
        uses: actions/checkout@v3
        with:
          repository: pharmpy/pharmpy.github.io
          path: pharmpy.github.io
          token: ${{secrets.DOC_TOKEN}}

      - uses: ./pharmpy/.github/actions/setup-tox
        with:
          python-version: "3.9"

      - name: Install graphviz
        run: sudo apt install graphviz

      - name: Run unit tests with tox
        run: |
          cd pharmpy
          tox -e unit

      - name: Build documentation
        run: |
          cd pharmpy
          tox -e docs-build

      - name: Install wheel
        run: |
          pip install wheel

      - name: Build wheel
        run: |
          cd pharmpy
          python setup.py bdist_wheel

      - name: Build source package
        run: |
          cd pharmpy
          python setup.py sdist --formats=gztar

      - name: Prepare upload files
        run: |
          cd pharmpy
          mkdir upload
          cp dist/*.whl dist/*.tar.gz upload

      - name: Wait for all other workflows to complete
        uses: lewagon/wait-on-check-action@v1
        with:
          ref: ${{ github.sha }}
          check-regexp: '.*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Publish documentation
        run: |
          cp -RT pharmpy/dist/docs/ pharmpy.github.io/latest/
          cd pharmpy.github.io
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Documentation update"
          git push https://$USERNAME:$REPO_KEY@github.com/pharmpy/pharmpy.github.io.git
        env:
          REPO_KEY: ${{secrets.DOC_TOKEN}}
          USERNAME: github-actions[bot]

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: pharmpy/upload/


  trigger-pharmr-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pharmr workflow
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -u "$USERNAME:$REPO_KEY" \
          https://api.github.com/repos/pharmpy/pharmr/actions/workflows/build_docs.yaml/dispatches \
          -d '{"ref":"main"}'
        env:
            REPO_KEY: ${{secrets.DOC_TOKEN}}
            USERNAME: github-actions[bot]
