name: main

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: build-ci

    strategy:
      matrix:
        suite: ['lint', 'unit', 'doctest', 'docs-build', 'docs-test', 'docs-lint']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        exclude:
          - platform: windows-latest
            python-version: '3.10'

    runs-on: ${{ matrix.platform }}

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Lint MANIFEST and Python files
        if: matrix.suite == 'lint'
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
          TOX_FACTOR: ${{ matrix.suite }}

      - name: Run tests with tox
        if: matrix.suite == 'unit' || matrix.suite == 'doctest'
        run: |
            tox
            echo "coverage=${{ matrix.suite }}" >> $GITHUB_ENV
        env:
          PLATFORM: ${{ matrix.platform }}
          TOX_FACTOR: ${{ matrix.suite }}

      - name: Upload coverage to Codecov
        if: env.coverage != ''
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ env.coverage }},${{ matrix.platform }},python-${{ matrix.python-version }}
          files: ./.coverage.xml

      - name: Build docs
        if: matrix.suite == 'docs-build' && matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.9'
        run: tox -e docs

      - name: Test docs
        if: matrix.suite == 'docs-test' && matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.9'
        run: tox -e sphinxtest

      - name: Lint docs
        if: matrix.suite == 'docs-lint' && matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.9'
        run: tox -e doccheck
