name: Test triggering of Pharmr workflow

on: workflow_dispatch

jobs:
  trigger-pharmr:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pharmr workflow
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -u "$USERNAME:$REPO_KEY" \
          https://api.github.com/repos/pharmpy/pharmr/actions/workflows/build_docs.yaml/dispatches \
          -d '{"ref":"main"}'
        env:
            REPO_KEY: ${{secrets.DOC_TOKEN}}
            USERNAME: github-actions[bot]
