name: test_deploy

on:
  workflow_dispatch:
  workflow_run:
      workflows: [ "CI" ]
      type:
          - complete

jobs:
  print_ci_complete:
      runs-on: ubuntu-latest
      steps:
          -   name: print
              run: echo "ci complete"
