name: Version update

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pharmpy/pharmpy
      uses: actions/checkout@v2
      with:
          path: pharmpy
