name: Test workflow wait

on: workflow_dispatch

jobs:
  wait-for-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Wait on version test
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.sha }}
          running-workflow-name: wait-for-tag
          check-name: test-tag
          repo-token: ${{ secrets.DOC_TOKEN }}
          wait-interval: 20
  wait-for-ci:
    needs: wait-for-tag
    runs-on: ubuntu-latest
    strategy:
        matrix:
          platform: [ubuntu-latest, macos-latest, windows-latest]
          python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@master
      - name: Wait on CI test
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.sha }}
          running-workflow-name: wait-for-ci
          check-name: build-ci (${{ matrix.platform }}, ${{ matrix.python-version }})
          repo-token: ${{ secrets.DOC_TOKEN }}
          wait-interval: 20
  print-successful:
      needs: wait-for-ci
      runs-on: ubuntu-latest
      steps:
        - name: print sucess
          run: echo "Sucess"
