name: Test workflow wait

on: push

jobs:
  wait-for-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Wait on version test
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.sha }}
          running-workflow-name: wait-for-tag
          repo-token: ${{ secrets.DOC_TOKEN }}
          wait-interval: 20
  print-successful:
      needs: wait-for-tag
      runs-on: ubuntu-latest
      steps:
        - name: print sucess
          run: echo "Sucess"
