name: Test workflow wait

on: push

jobs:
  wait-for-tag:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Wait on version test
          uses: lewagon/wait-on-check-action@v0.2
          with:
            ref: ${{ github.sha }}
            running-workflow-name: wait-for-tag
            check-name: test-tag
            repo-token: ${{ secrets.DOC_TOKEN }}
            wait-interval: 20
  wait-for-ci:
    needs: test-tag
    runs-on: ubuntu-latest
    steps:
      - name: CI test
        run: |
          echo "CI"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: pharmpy
          repo: pharmpy
          github_token: ${{ secrets.DOC_TOKEN }}
          workflow_file_name: main.yml
  print-successful:
      needs: test-ci
      runs-on: ubuntu-latest
      steps:
        - name: print sucess
          run: echo "Sucess"
