name: Test workflow wait

on:
  workflow_run:
    workflows: ["Version tags"]
    branches: [master]
    types:
      - completed

jobs:
  test-wait:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Print success message
      run: echo "Succcess"
  test-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
    - name: Print failure message
      run: echo "Failure"
