name: Test workflow wait

on: push

jobs:
  test-wait:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Wait for tests to run
      run: echo "Wait"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pharmpy/pharmpy
      uses: actions/checkout@v2
      with:
          path: pharmpy
