name: Test workflow wait

on:
  push:

jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Version tags test
      run: |
        echo "Version tags"
        sleep 10s
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: pharmpy
        repo: pharmpy
        github_token: ${{ secrets.DOC_TOKEN }}
        workflow_file_name: test-tag-workflow.yml
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - name: CI test
        run: |
          echo "CI"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: pharmpy
          repo: pharmpy
          github_token: ${{ secrets.DOC_TOKEN }}
          workflow_file_name: main.yml
  print-successful:
      runs-on: ubuntu-latest
      steps:
        - name: print sucess
          run: echo "Sucess"
      
