name: Test workflow wait

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  test-wait:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pharmpy/pharmpy
      uses: actions/checkout@v2
      with:
          path: pharmpy
